server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password:
  redis:
    host:
    password: